# Generated by Django 5.2.9 on 2025-12-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatlog',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
